{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-metbrewer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MetBrewer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MetBrewer/MetBrewer_{{ version }}.tar.gz
  sha256: e7be2881416d909672462d49c6cc82aa63132423102765f3208036967e79a174

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
  run:
    - r-base
    - r-ggplot2

test:
  commands:
    - $R -e "library('MetBrewer')"           # [not win]
    - "\"%R%\" -e \"library('MetBrewer')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=MetBrewer
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE.md
  summary: Palettes Inspired by Works at the Metropolitan Museum of Art in New York. Currently contains 50 color schemes and checks for colorblind-friendliness of palettes. Colorblind accessibility checked using Jakub Nowosad's package 'colorblindcheck'<https://nowosad.github.io/colorblindcheck/>.


extra:
  recipe-maintainers:
    - conda-forge/r
    - mfansler

# Package: MetBrewer
# Type: Package
# Title: Color Palettes Inspired by Works at the Metropolitan Museum of Art
# Version: 0.1.0
# Author: Blake Robert Mills
# Maintainer: Blake Robert Mills <blakerobertmills@gmail.com>
# Description: Palettes Inspired by Works at the Metropolitan Museum of Art in New York. Currently contains 50 color schemes and checks for colorblind-friendliness of palettes. Colorblind accessibility checked using Jakub Nowosad's package 'colorblindcheck'<https://nowosad.github.io/colorblindcheck/>.
# License: CC0
# Encoding: UTF-8
# RoxygenNote: 7.1.2
# Suggests: ggplot2
# NeedsCompilation: no
# Packaged: 2022-01-04 15:07:51 UTC; blake
# Repository: CRAN
# Date/Publication: 2022-01-05 09:50:09 UTC
